### ISSUE TITLE
Adjust Goal Types and Update Life Cycle Handling

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#402]
`test-manager` needs to be updated to ensure it can handle single execution for `load`:
- add selection strategy for one experiment - `SingleExperimentSelectionStrategy`
- add validation strategy for one experiment - `SingleExperimentValidationStrategy`

**Comment by VincenzoFerme** [comment]
You name them `SingleExperiment...`, meaning that they can be used for any type of goals performing a single experiment?

**Comment by jeppe-style** [comment]
yes exactly

**Comment by VincenzoFerme** [comment]
Why exactly do we need to know in the lifecycle that is a single experiment that has to be executed?

**Comment by jeppe-style** [comment]
There is no exploration space defined which means if we generate an exploration space the size would be 0, therefore I think it is cleaner to separate this into its own strategy rather than adding workarounds to existing strategies.

**Comment by VincenzoFerme** [comment]
As discussed: 

- There is an exploration space with a single point, so its cardinality is `1`
- What you propose is a workaround to the design you currently have, because you need to add something different to add a case that can be integrated in your current design in the following way:
   - Have an exploration space with one point
   - Keep the single experiment selection and validation strategy you defined here
   - The `goal` determine the strategy to be enabled, if not overridden by the user
   - Handle everything as in the other cases, but the lifecycle ends after the single experiment is executed

Given that we had to merge https://github.com/benchflow/benchflow/pull/466, we opened [another issue](https://github.com/benchflow/benchflow/issues/486) to improve the current implementation.
