### ISSUE TITLE
Add links in REST API response objects

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#445]
**Run BenchFlow Test**
- [x] link to test status (`status: URL`)

**Test Status**
Test Model
- [x] link to test bundle on minio (`testBundle: URL`)

Experiment Model
- [x] link to experiment bundle on minio (`experimentBundle: URL`)
- [x] link to collected data on minio (`collectedData: URL`)
- [x] link to experiment status on experiment-manager (`status: URL`)

Related to https://github.com/benchflow/benchflow/issues/128

**Comment by VincenzoFerme** [comment]
Since these link can change, we need to carefully design a place in the system where the information they are based on, can be specified. The Base URL has to be anyway retrieved from the configuration file I think.

The link to Minio should be to the container "folder" because otherwise I think they just download the file instead of visualising it (that can also be ok).

On Minio we do not have results, but collected data. There will be a link to results, that is going to be probably a link to a Notebook preloading a template to access and query the data, for now.

**Comment by jeppe-style** [comment]
ok - I updated and wrote `link to collected data on minio`

for the rest it is fine?

**Comment by VincenzoFerme** [comment]
The drop wizard configuration can express the reference to the services using an hostname, that is resolved using the DNS service of the infrastructure on which we deploy BenchFlow, in our case currently Rancher. That said, you should determine if the specified server is a valid and reachable IP address, or you need to [convert it to a valid IP](https://stackoverflow.com/questions/15788453/resolving-ip-address-of-a-hostname). This should happen when you load the configuration information, by adding extra fields to the configurations made available to the service.

**Comment by VincenzoFerme** [comment]
TODOs:
- Moreover, do not save URLs to the database, they need to be generated on the fly and they should be positioned in a dedicated section in the response, not mixed with other fields, see: https://github.com/benchflow/benchflow/issues/128#issuecomment-313679357.. The fields should only contain human readable data, so if you want to extend some of them with actual content feel free to do so.
- `collectedData: URL` misses full path (needs hash, not sure of what)

**Comment by VincenzoFerme** [comment]
What is left from this Issue is now documented in https://github.com/benchflow/benchflow/issues/128#issuecomment-319903870
